<?php

namespace CinemaHD\Repositories;

/**
 * MoviesHasPeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesHasPeopleRepository extends \Doctrine\ORM\EntityRepository
{

}
