<?php

namespace CinemaHD\Repositories;

use CinemaHD\Entities\Movie;
use CinemaHD\Entities\People;

/**
 * MovieHasPeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieHasPeopleRepository extends \Doctrine\ORM\EntityRepository
{
}
