<?php

namespace CinemaHD\Repositories;

use CinemaHD\Entities\Type;
use CinemaHD\Entities\Movie;
use CinemaHD\Entities\MovieHasType;

/**
 * MovieHasTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieHasTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
