<?php

namespace CinemaHD\Repositories;

/**
 * MoviesHasTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesHasTypeRepository extends \Doctrine\ORM\EntityRepository
{

}
