<?php

namespace CinemaHD\Repositories;

/**
 * OrderHasTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHasTicketRepository extends \Doctrine\ORM\EntityRepository
{

}
