<?php

namespace CinemaHD\Repositories;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPrices()
    {
        $dql   = "SELECT price
            FROM CinemaHD\Entities\Price price
            WHERE 1 = 1
        ";
        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }
}
