<?php

namespace CinemaHD\Repositories;

/**
 * SpectatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpectatorRepository extends \Doctrine\ORM\EntityRepository
{

}
